---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: druid-server-tls
  namespace: data-science
spec:
  secretName: druid-server-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "druid.samcloud.online"
  dnsNames:
    - "druid.samcloud.online"
    - "druid-router.data-science.svc.cluster.local"
    - "druid-coordinator.data-science.svc.cluster.local"
    - "druid-broker.data-science.svc.cluster.local"
    - "druid-historical.data-science.svc.cluster.local"
    - "druid-overlord.data-science.svc.cluster.local"
    - "druid-middlemanager.data-science.svc.cluster.local"
    - "localhost"
  ipAddresses:
    - "127.0.0.1"
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: druid-client-tls
  namespace: data-science
spec:
  secretName: druid-client-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "druid-client"
  dnsNames:
    - "druid-client"
  usages:
    - digital signature
    - key encipherment
    - client auth