---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./certificate.yaml
  - ./networkpolicy.yaml
  - ./servicemonitor.yaml
  - ./prometheusrule.yaml
  - ./rbac.yaml
  - ./ingress.yaml
  - ./helmrelease.yaml
  - ./configmap.yaml
  - ./pdb.yaml
  - ./hpa.yaml
  - ./psp.yaml
  - ./grafana-dashboard.yaml
  - ./security-audit.yaml