---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smokeping-config-v1
  namespace: observability
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Mi
  storageClassName: openebs-hostpath
