---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cloudnative-pg-analytics-coordinator
  namespace: storage
spec:
  minAvailable: 2
  selector:
    matchLabels:
      cnpg.io/cluster: cloudnative-pg-analytics-coordinator
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cloudnative-pg-analytics-coordinator
  namespace: storage
spec:
  minAvailable: 1
  selector:
    matchLabels:
      cnpg.io/cluster: cloudnative-pg-analytics-coordinator
      cnpg.io/instanceRole: primary 