---
apiVersion: v1
kind: Service
metadata:
  name: cloudnative-pg-analytics-coordinator
  annotations:
    external-dns.alpha.kubernetes.io/hostname: cloudnative-pg-analytics-coordinator.samcloud.online
    lbipam.cilium.io/ips: 192.168.8.106
spec:
  type: LoadBalancer
  ports:
    - name: cloudnative-pg-analytics-coordinator
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: cloudnative-pg-analytics-coordinator
    role: primary