---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 30m
  install:
    createNamespace: true
  values:
    controllers:
      uptime-kuma:
        containers:
          app:
            env:
              TZ: "${TZ}"
              UPTIME_KUMA_DATA_DIR: &datadir /uptime-kuma-data
            image:
              repository: louislam/uptime-kuma
              tag: 1.23.16@sha256:431fee3be822b04861cf0e35daf4beef6b7cb37391c5f26c3ad6e12ce280fe18
            ports:
              - name: http
                containerPort: 3001
                protocol: TCP
            resources:
              requests:
                cpu: 10m
                memory: 50Mi
              limits:
                memory: 150Mi
    service:
      app:
        controller: uptime-kuma
        ports:
          http:
            port: 3001
            protocol: TCP
            targetPort: 3001
    serviceMonitor:
      app:
        serviceName: uptime-kuma
        endpoints:
          - port: http
    route:
      app:
        hostnames: ["{{ .Release.Name }}.samcloud.online"]
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: 3001
    persistence:
      config:
        enabled: true
        existingClaim: uptime-kuma-data
        globalMounts:
          - path: *datadir
