---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage

resources:
  - ./backup-strategy.yaml

commonLabels:
  app.kubernetes.io/name: patroni
  app.kubernetes.io/component: backup
  app.kubernetes.io/part-of: postgresql
  environment: production

commonAnnotations:
  backup.velero.io/enabled: "true"
  backup.retention.policy: "30d" 