---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: blocky
  namespace: observability
spec:
  staticConfigs:
    - targets:
        - blocky.samcloud.online
  metricsPath: /metrics
