---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name gotify-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        INIT_POSTGRES_HOST: &dbhost "{{ .POSTGRES_GENERIC_APP_HOST }}"
        INIT_POSTGRES_PORT: &dbport 5432
        INIT_POSTGRES_SSLMODE: &dbsslmode disable
        INIT_POSTGRES_DBNAME: &dbname gotify
        INIT_POSTGRES_USER: &dbuser "gotify"
        INIT_POSTGRES_PASS: &dbpass "{{ .POSTGRES_GENERIC_APP_PASSWORD }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        GOTIFY_DEFAULTUSER_NAME: "{{ .GOTIFY_DEFAULTUSER_NAME }}"
        GOTIFY_DEFAULTUSER_PASS: "{{ .GOTIFY_DEFAULTUSER_PASS }}"
        GOTIFY_DATABASE_CONNECTION: |-
          host='{{ .INIT_POSTGRES_HOST }}' port=5432 user='gotify' dbname='gotify' password='{{ .POSTGRES_GENERIC_APP_PASSWORD }}' sslmode=disable
  dataFrom:
    - extract:
        key: gotify
    - extract:
        key: cloudnativepg
