---
# Analytics Credentials
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-analytics-credentials
  namespace: storage
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: credentials
    app.kubernetes.io/part-of: postgresql
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: postgres-analytics-credentials
    creationPolicy: Owner
  data:
    - secretKey: ANALYTICS_USER
      remoteRef:
        key: postgres-analytics-credentials
        property: ANALYTICS_USER
    - secretKey: ANALYTICS_PASSWORD
      remoteRef:
        key: postgres-analytics-credentials
        property: ANALYTICS_PASSWORD
  