---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postgres-analytics-pdb
  namespace: storage
spec:
  minAvailable: 2
  selector:
    matchLabels:
      cnpg.io/cluster: postgres-analytics
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postgres-analytics-primary-pdb
  namespace: storage
spec:
  minAvailable: 1
  selector:
    matchLabels:
      cnpg.io/cluster: postgres-analytics
      cnpg.io/instanceRole: primary 