---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-query-accelerator
  namespace: storage
  labels:
    app.kubernetes.io/name: query-accelerator
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: postgresql
automountServiceAccountToken: true