---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age1pne9nvyh4n25fqwn3pdvykrpd5jxm6gazcpmtkgmg9xpy3vfv96qwxmehh"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age1pne9nvyh4n25fqwn3pdvykrpd5jxm6gazcpmtkgmg9xpy3vfv96qwxmehh"
stores:
  yaml:
    indent: 2
