apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup
    namespace: storage
    labels:
        reloader.stakater.com/auto: "true"
stringData:
     minio_access_key_id: "kgTGG8uBGrNm41sETl5M"
     minio_secret_access_key: "62TAHCb4tDwgNSnJM8mEAkDQE0pUQ6IhhcYXiSvU"
     s3_endpoint_url: "http://192.168.8.161:9000"
     s3_bucket_name: "postgres-backup"



     