apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-analytics-coordinator
    namespace: storage
    labels:
        reloader.stakater.com/auto: "true"
stringData:
     username: "postgres"
     password: "postgres"