apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: observability
type: Opaque
stringData:
    objstore.yml: |
        type: S3
        config:
            bucket: thanos
            endpoint: http://192.168.8.161:9000
            insecure: true
            access_key: cQY7QVBJIgVgsAVid4Pn
            secret_key: G4k80oDO4CimiD3UydmkrUCia4Ll4SKNJm2mOOyL
