---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: adguard-home
  namespace: network
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: adguard-home
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        adguard_username: "{{ .adguard_username }}"
        adguard_password_hash: "{{ .adguard_password_hash }}"
        adguard_session_key: "{{ .adguard_session_key }}"
  dataFrom:
    - extract:
        key: adguard-home
  refreshInterval: 15m 