---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-home-config
  namespace: network
  labels:
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-home-data
  namespace: network
  labels:
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 10Gi 