---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg
  namespace: &namespace storage
spec:
  dependsOn:
    - name: onepassword
      namespace: security
  interval: 30m
  path: ./kubernetes/apps/storage/cloudnative-pg/app
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: storage
  timeout: 3m
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg-cluster
  namespace: &namespace storage
spec:
  dependsOn:
    - name: cloudnative-pg
      namespace: storage
    - name: openebs
      namespace: storage
  interval: 30m
  path: ./kubernetes/apps/storage/cloudnative-pg/cluster
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: storage
  timeout: 3m
  wait: true
