---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubecost-backup
  namespace: finops
  labels:
    app.kubernetes.io/name: kubecost
    app.kubernetes.io/component: backup
    app.kubernetes.io/part-of: finops-platform
automountServiceAccountToken: false 