apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-credentials
  namespace: storage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: redis-credentials
    template:
      engineVersion: v2
      data:
        redis-password: "{{ .redis_password }}"
  data:
    - secretKey: redis_password
      remoteRef:
        key: redis
        property: password