---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: redis-restricted
  namespace: storage
spec:
  allowHostDirVolumePlugin: false
  allowHostIPC: false
  allowHostNetwork: false
  allowHostPID: false
  allowHostPorts: false
  allowPrivilegeEscalation: false
  allowPrivilegedContainer: false
  allowedCapabilities: []
  defaultAddCapabilities: []
  fsGroup:
    type: MustRunAs
    ranges:
      - min: 1001
        max: 1001
  readOnlyRootFilesystem: true
  requiredDropCapabilities:
    - ALL
  runAsUser:
    type: MustRunAs
    uid: 1001
  seLinuxContext:
    type: MustRunAs
  supplementalGroups:
    type: MustRunAs
    ranges:
      - min: 1001
        max: 1001
  volumes:
    - configMap
    - downwardAPI
    - emptyDir
    - persistentVolumeClaim
    - projected
    - secret