apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-tls-cert
  namespace: data
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: redis-tls-cert
    template:
      engineVersion: v2
      data:
        tls.crt: "{{ .tls_certificate }}"
        tls.key: "{{ .tls_key }}"
        ca.crt: "{{ .ca_certificate }}"
  data:
    - secretKey: tls_certificate
      remoteRef:
        key: redis-tls
        property: certificate
    - secretKey: tls_key
      remoteRef:
        key: redis-tls
        property: private_key
    - secretKey: ca_certificate
      remoteRef:
        key: redis-tls
        property: ca_certificate