# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app stirling-pdf
  namespace: services
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "4.1.0"  # Update this to your desired chart version
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000  # Ensures proper file permissions

    controllers:
      stirling-pdf:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          enableServiceLinks: false
          volumes:
            - name: logs
              emptyDir: {}
            - name: config
              emptyDir: {}

          volumeMounts:
            - name: logs
              mountPath: /logs
            - name: config
              mountPath: /config

        initContainers:
          - name: init-dirs
            image: busybox
            command: ['sh', '-c', 'mkdir -p /logs /config && chown -R 1000:1000 /logs /config']
            volumeMounts:
              - name: logs
                mountPath: /logs
              - name: config
                mountPath: /config

        containers:
          app:
            image:
              repository: ghcr.io/frooodle/s-pdf
              tag: 0.18.1@sha256:8967366617998d99ce8f71af9041302e5ee6bd007d8d603456716a54e928eaf7

            env:
              TZ: UTC
              STIRLING_PDF_DATA_DIR: &datadir /data
              USER_UID: 1000
              USER_GID: 1000
              LOGGING_FILE_PATH: /logs
              LOGGING_FILE_NAME: application.log

            resources:
              requests:
                cpu: 100m
                memory: 250Mi
              limits:
                memory: 512Mi

    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 8080

    route:
      app:
        hostnames:
          - "pdf.samcloud.online"
        parentRefs:
          - name: external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port

    persistence:
      config:
        enabled: true
        existingClaim: stirlingpdf-pvc
        globalMounts:
          - path: *datadir
            subPath: stirling-pdf
