---
  # yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
  apiVersion: helm.toolkit.fluxcd.io/v2
  kind: HelmRelease
  metadata:
    name: &app trilium
    namespace: services
  spec:
    interval: 5m

    chart:
      spec:
        chart: app-template
        version: 4.0.1
        sourceRef:
          kind: HelmRepository
          name: bjw-s
          namespace: flux-system
    releaseName: trilium
    targetNamespace: services
    maxHistory: 2

    install:
      createNamespace: true
      remediation:
        retries: 3

    upgrade:
      cleanupOnFail: true
      remediation:
        strategy: rollback
        retries: 3

    uninstall:
      keepHistory: false

    values:

      controllers:
        trilium:
          annotations:
            reloader.stakater.com/auto: "true"
          containers:
            *app :
              image:
                repository: triliumnext/notes
                tag: v0.93.0
              env:
                TZ: UTC
                TRILIUM_DATA_DIR: &datadir /trilium-data
                USER_UID: 1000
                USER_GID: 1000
              resources:
                requests:
                  cpu: 100m
                  memory: 100Mi
                limits:
                  memory: 2Gi
              

      service:
        *app :
          controller: *app
          ports:
            http:
              port: &port 8080

      ingress:
        app:
          enabled: true
          className: external
          annotations:
            external-dns.alpha.kubernetes.io/target: external.samcloud.online
          hosts:
            - host: &host "{{ .Release.Name }}.samcloud.online"
              paths:
                - path: /
                  service:
                    identifier: *app
                    port: *port
          tls:
            - hosts:
                - *host
      persistence:
        config:
          enabled: true
          existingClaim: trilium-pvc
          globalMounts:
            - path: *datadir
