---
  # yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
  apiVersion: helm.toolkit.fluxcd.io/v2
  kind: HelmRelease
  metadata:
    name: &app trilium
    namespace: services
  spec:
    interval: 5m

    chart:
      spec:
        chart: app-template
        version: 4.0.1
        sourceRef:
          kind: HelmRepository
          name: bjw-s
          namespace: flux-system
    releaseName: trilium
    targetNamespace: services
    maxHistory: 2

    install:
      createNamespace: true
      remediation:
        retries: 3

    upgrade:
      cleanupOnFail: true
      remediation:
        strategy: rollback
        retries: 3
    dependsOn:
      - name: cloudflare-tunnel
        namespace: network
    uninstall:
      keepHistory: false

    values:

      controllers:
        trilium:
          annotations:
            reloader.stakater.com/auto: "true"
          containers:
            *app :
              image:
                repository: triliumnext/notes
                tag: v0.91.6
              env:
                TZ: UTC
                TRILIUM_DATA_DIR: &datadir /trilium-data
                USER_UID: 1000
                USER_GID: 1000
              resources:
                requests:
                  cpu: 100m
                  memory: 100Mi
                limits:
                  memory: 2Gi

      service:
        *app :
          controller: *app
          ports:
            http:
              port: &port 8080
      serviceMonitor:
        app:
          serviceName: *app
          endpoints:
            - port: http
      route:
        app:
          hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
          parentRefs:
            - name: external
              namespace: kube-system
              sectionName: https
          rules:
            - backendRefs:
                - identifier: app
                  port: *port

      persistence:
        config:
          enabled: true
          existingClaim: trilium-pvc
          globalMounts:
            - path: *datadir
