# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  namespace: services
  name: trilium
spec:
  interval: 5m
  targetNamespace: services
  chartRef:
    kind: HelmRepository
    name: bjw-s
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  values:
    controllers:
      app:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: triliumnext/notes
              tag: v0.91.6
            env:
              TZ: UTC
              TRILIUM_DATA_DIR: &datadir /trilium-data
              USER_UID: 1000
              USER_GID: 1000
            resources:
              requests:
                cpu: 100m
                memory: 100Mi
              limits:
                memory: 2Gi
    service:
      app:
        controller: app
        ports:
          http:
            port: &port 8080
    ingress:
      app:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.samcloud.online
        hosts:
          - host: "{{ .Release.Name }}.samcloud.online"
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: app
                    port:
                      number: *port
        tls:
          - hosts:
              - "{{ .Release.Name }}.samcloud.online"
            secretName: trilium-tls
    persistence:
      config:
        enabled: true
        existingClaim: trilium-pvc
        globalMounts:
          - path: *datadir
