# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:e/idygkFiAhezdthbQ0WTkfDdakDh7vsbYesizLdno7OtHDXFWICIQ==,iv:dyy9eDayMpYTKa5lem4W1VzA6CVvqvxE9rjfQPEq+ug=,tag:5VH06f0aBanY+MCEYSo31Q==,type:str]
sops:
  age:
    - recipient: age1pne9nvyh4n25fqwn3pdvykrpd5jxm6gazcpmtkgmg9xpy3vfv96qwxmehh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdkR2NmdaWmlJbUNEdTNF
        ZDJiTHhrdU1Sbm43ano4VGZVY0pKeEs0dDE4CndVV3J4ejg2OXpVMFUrenJSSzZn
        Z01LY0FVMGlmWkJWOWNzS3o3MGN1UFkKLS0tIHpZRG51Y0sxVXVmRU1OWTVaWWYx
        eUlZRjU1SWxRQ1VQRVU4SXVIYlRwb00K/awuXIjTrM2/mLTnqnpF9FSLbaoQqjNO
        9Un2ni0Qhe6u/WTr7JrT7x3ddThJjp7WNKj/cI5YcRUH8t3hqW44oA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-14T22:32:27Z"
  mac: ENC[AES256_GCM,data:y0boS+FI3GqHGntira8gx7AEbR66BkCxm4YZnJTwz5X4CVgaVnsUgf83GpjZQI+cOVvphK/MWlRBTHfT0WivL6yfh4HDypDVzsWqFwos+v4TaH9pEyGC/olS05ZiHjsOH5AT1QN7+jbBFnMUTR+OeRGVo4ay0dye6R2niD/YZ7A=,iv:UHlCVWjsFzRJGWKpsFm5S9eNXyn/FX6dUXTKrKUdC6U=,tag:5VHDOD0XocwCDJczo532tA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
