# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:Ti3JTQ2oUDTf95MpItHzExmzCPxI1U9qIORtt8iCVrBa8jatGUyKsQ==,iv:GdpU5S3cnvAq6g+2AKt3QSFdgQRjJvukslyYBt8u34s=,tag:Y8f0lZANgEDGJadUFpBMSw==,type:str]
sops:
  age:
    - recipient: age1tudjnu8ra4zdanrhph0dhmdl8r4u0u6pfcwu0r4ayjtzja724vxqzfqjqt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzeE1WZXcxb3lTUUlmSkll
        dFB1c1VRSmZ2ZVN6REdqbHJqVEFIa2EyNW5BCjJ3c3Y5cGJ3WVhTa3NwSGNodzc2
        RUNzQTJRM2dtU1Z3YVNneGJuLzF1Rm8KLS0tIDJKL3ZYMmdPdHRybzB0eEJBVW1M
        aHVJUVI3aXBLcUtGenRnRExvQ2ZXSm8KliNF7NJv+iBj6/DOK6BlQo+Kz+bpNx+j
        6RK3uzkVqaOF62pUtF0sJjnyxtcCopBgESVcJRM9MpPPF2I5aqfdng==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-31T08:30:35Z"
  mac: ENC[AES256_GCM,data:6x+dS5InJKSQujYhN+K++/ZBKTJ0kOHwmS/z+s3l0hFQuAekm5KuaGZ7yU0csLJyGNEGgeb4TfjenymQUanAOe0t95MKqdVCSEDFl28RtneNocP3wHBBQcElM1rjE21G+8MxnpC/u2A+Ymw4R88y83Nw2U9twl7OM+n7dySDGEY=,iv:45sIaRRQKTfjlXlxpyjG8TtiTeS4def6aDqsKnPpceU=,tag:1yLWeiws9F4UqWZHYNBxHA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
