---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: postgres-loadbalancing
  labels:
    app.kubernetes.io/name: postgres-loadbalancing
    app.kubernetes.io/component: loadbalancer
    app.kubernetes.io/part-of: postgresql

resources:
  - ./configmap.yaml
  - ./rbac.yaml
  - ./services.yaml
  - ./hpa.yaml
  - ./helmrelease.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: cloudnative-pg
      app.kubernetes.io/component: loadbalancing
      app.kubernetes.io/part-of: postgresql