---
# HAProxy Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: haproxy
  namespace: storage
  labels:
    app.kubernetes.io/name: haproxy
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: postgresql
automountServiceAccountToken: true