# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: thanos-credentials
  namespace: observability
spec:
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        access_key: "{{ .access_key }}"
        secret_key: "{{ .secret_key }}"
  refreshInterval: 15m
  dataFrom:
    - extract:
        key: minio_tf_thanos
