---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: thanos
  namespace: observability
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: thanos
      version: 1.20.0
      sourceRef:
        kind: HelmRepository
        name: stevehipwell
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: kube-prometheus-stack
      namespace: observability
    - name: openebs
      namespace: storage

  values:
    objstoreConfig:
      type: s3
      config:
        bucket: thanos
        endpoint: "s3.garb.dev"
        region: us-east-1
        insecure: true
    additionalEndpoints:
      - dnssrv+_grpc._tcp.prometheus-kube-prometheus-thanos-discovery.observability.svc.cluster.local
    additionalReplicaLabels: ["__replica__"]
    serviceMonitor:
      enabled: true
    compactor:
      enabled: true
      extraArgs:
        - --compact.concurrency=4
        - --delete-delay=30m
        - --retention.resolution-raw=14d
        - --retention.resolution-5m=30d
        - --retention.resolution-1h=60d
      persistence: &persistence
        enabled: true
        storageClass: openebs-hostpath
        size: 10Gi
      nodeSelector:
        node-role.kubernetes.io/worker: ""
    query:
      enabled: true
      replicas: 2
      extraArgs: ["--alert.query-url=https://thanos.samcloud.online"]
      additionalStores: ["thanos-svc.samcloud.online:10901"]
      nodeSelector:
        node-role.kubernetes.io/worker: ""
    queryFrontend:
      enabled: true
      replicas: 2
      extraEnv: &extraEnv
        - name: THANOS_CACHE_CONFIG
          valueFrom:
            configMapKeyRef:
              name: &configMap thanos-cache-configmap
              key: cache.yaml
      extraArgs: ["--query-range.response-cache-config=$(THANOS_CACHE_CONFIG)"]
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      ingress:
        enabled: true
        ingressClassName: internal
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - &host thanos-query-frontend.samcloud.online
        tls:
          - hosts:
              - *host
      podAnnotations: &podAnnotations
        configmap.reloader.stakater.com/reload: *configMap
    rule:
      enabled: true
      replicas: 2
      extraArgs: ["--web.prefix-header=X-Forwarded-Prefix"]
      alertmanagersConfig:
        value: |-
          alertmanagers:
            - api_version: v2
              static_configs:
                - dnssrv+_http-web._tcp.alertmanager-operated.monitoring.svc.cluster.local
      rules:
        value: |-
          groups:
          - name: PrometheusWatcher
            rules:
              - alert: PrometheusDown
                annotations:
                  summary: A Prometheus has disappeared from Prometheus target discovery
                expr: absent(up{job="prometheus-kube-prometheus-operator"})
                for: 5m
                labels:
                  severity: critical
    storeGateway:
      replicas: 2
      extraEnv: *extraEnv
      extraArgs: ["--index-cache.config=$(THANOS_CACHE_CONFIG)"]
      persistence: *persistence
      podAnnotations: *podAnnotations
      nodeSelector:
        node-role.kubernetes.io/worker: ""
  valuesFrom:
    - targetPath: objstoreConfig.config.access_key
      kind: Secret
      name: thanos-credentials
      valuesKey: access_key
    - targetPath: objstoreConfig.config.secret_key
      kind: Secret
      name: thanos-credentials
      valuesKey: secret_key
