---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: ts-lbs
  annotations:
    tailscale.com/proxy-group: ingress-proxy
spec:
  hostname: ts-lbs
  subnetRouter:
    advertiseRoutes:
      - "192.168.8.1/24"
