---
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: "worker.tail096cd8.ts.net"
    tailscale.com/proxy-group: "ingress-proxy"
  name: ts-ollama
spec:
  externalName: placeholder 
  type: ExternalName
  ports:
    - port: 11434
      protocol: TCP
      name: http 