---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app filebrowser
  namespace: &namespace services
spec:
  targetNamespace: services
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  # components:
  #   - ../../../../components/volsync
  #   - ../../../../components/security-policy/forward-auth
  #   - ../../../../components/keda/nfs-scaler
  path: ./kubernetes/apps/default/filebrowser/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  # postBuild:
  #   substitute:
  #     APP: *app
  #     VOLSYNC_CAPACITY: 1Gi
