# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:cFrvIiYQ2VSqsVarcpALOG1varoqKjTGyp28A5HTDCA=,iv:yF/6uqDMy/F/BlMHDPCwTnSXQI67JcMgR7pGBZXuFUo=,tag:wGH9wK6v3c0GwP6PmCIr3w==,type:str]
sops:
  age:
    - recipient: age1pne9nvyh4n25fqwn3pdvykrpd5jxm6gazcpmtkgmg9xpy3vfv96qwxmehh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1L0tHbGRRVzNWVXpHTkoz
        bmptdHFiYzFJOUp2akNPak9wL0NtRFRURFNRCjJuYkVha0cyWHRjcTdkMkVNM2ZP
        ZlA1RitBaVZpbFFSVjJ5TnBwK2VacTQKLS0tIFVmVFl3L2IrRVRYS0xEM2NpcUo4
        WUhtTy9kdGxxaFRieW1BOVE1Y0pRUzgKj7E0YHTDgHEmkgrGWSorRvGZhZpbQ5nI
        58/zSr7JXyGZ4n+z3BguKUk89JsatJ01K05/KLjGhMZmpGIlqx1EMg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-14T22:32:27Z"
  mac: ENC[AES256_GCM,data:6LKtIHXewQiyC43OYAvi0znZodBJUuZcjD8VZnSn+gVCalH5eRDEywo9FbHTt8O1NPbVoYc3RAdX2i6bMiKGK2r4Y05yh+emDFbh6DH46wLD1T4kjheQHbDrTEwu6Tq9TuWbymnwVJIzUP9aw2S8NJ/XmQV82NjlwbOCGPQTOXc=,iv:5xs3KVH8mmFtvptwjBO8AeXcUSgQw8TXlh8BPL4UAPs=,tag:lxXyoE0iBaELlbArMCAkiQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
