---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cloudnative-pg-analytics-worker-two-pdb
  namespace: storage
  labels:
    citus-cluster: cloudnative-pg-analytics-worker-two
spec:
  minAvailable: 2
  selector:
    matchLabels:
      cnpg.io/cluster: cloudnative-pg-analytics-worker-two
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cloudnative-pg-analytics-worker-two-primary-pdb
  namespace: storage
  labels:
    citus-cluster: cloudnative-pg-analytics-worker-two
spec:
  minAvailable: 1
  selector:
    matchLabels:
      cnpg.io/cluster: cloudnative-pg-analytics-worker-two
      cnpg.io/instanceRole: primary 