---
apiVersion: v1
kind: Service
metadata:
  name: cloudnative-pg-analytics-worker-two
  annotations:
    external-dns.alpha.kubernetes.io/hostname: cloudnative-pg-analytics-worker-two.samcloud.online
    lbipam.cilium.io/ips: 192.168.8.108
spec:
  type: LoadBalancer
  ports:
    - name: cloudnative-pg-analytics-worker-two
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: cloudnative-pg-analytics-worker-two
    role: primary