apiVersion: v1
kind: Secret
metadata:
  name: slack-webhook-secret
  namespace: ci-cd
  labels:
    app.kubernetes.io/name: actions-runner-controller
    app.kubernetes.io/part-of: actions-runner-controller
stringData:
    SLACK_WEBHOOK: ENC[AES256_GCM,data:your-encrypted-slack-webhook-url-here,type:str]