---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudnative-pg
  namespace: storage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudnative-pg
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        pg_username: "{{ .pg_username }}"
        pg_password: "{{ .pg_password }}"
        minio_access_key_id: "{{ .minio_access_key_id }}"
        minio_secret_access_key: "{{ .minio_secret_access_key }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
