---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: it-tools-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 8Gi
  storageClassName: openebs-hostpath
