apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: snapshot-controller
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName: 'runtime/default'
    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
    apparmor.security.beta.kubernetes.io/defaultProfileName: 'runtime/default'
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'MustRunAsNonRoot'
    ranges:
      - min: 65532
        max: 65532
  runAsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 65532
        max: 65532
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 65532
        max: 65532
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 65532
        max: 65532
  readOnlyRootFilesystem: true
  forbiddenSysctls:
    - '*'