---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: storage-secrets
  namespace: storage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: storage-secrets
    template:
      engineVersion: v2
      data:
        STORAGE_ENCRYPTION_KEY: "{{ .STORAGE_ENCRYPTION_KEY }}"
        SLACK_WEBHOOK_URL: "{{ .SLACK_WEBHOOK_URL }}"
  data:
    - secretKey: STORAGE_ENCRYPTION_KEY
      remoteRef:
        key: storage-encryption
        property: key
    - secretKey: SLACK_WEBHOOK_URL
      remoteRef:
        key: storage-notifications
        property: slack-webhook