
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: snapshot-controller
  namespace: storage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: snapshot-controller
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        storage_encryption_key: "{{ .storage_encryption_key }}"
        slack_webhook_url: "{{ .slack_webhook_url }}"
  dataFrom:
    - extract:
        key: snapshot-controller
