# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:W3Sd+McQomRz0iXgt5FW7Zp2OR4wsNHlA1KvkYcI83EKJMb9d2InDLxg74jcpF4pGgKvisfsRyQxC9J8V5x51Gze8EHnp1jO4WV8BEkG0fwDxyoc01FjdNHJExNSGBaOQAKFY1fLCVOn48X29iMug/5QJakeIvqCAhRFeEflZ6U9XmzJ4x5pMSyCsE2J8VNiTC6g5fFdbXbMG4XzUoxtCJN1M36etLjEGY0FP7+EIs+Vquvj,iv:gbyPeH6qzESQK5gWgXsemyEIck47TQm6qNg8bfuA+1o=,tag:fnCoqMbJ88JreZlochoG5g==,type:str]
sops:
  age:
    - recipient: age1pne9nvyh4n25fqwn3pdvykrpd5jxm6gazcpmtkgmg9xpy3vfv96qwxmehh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RkltUGVaZlRPVDJxZDU1
        Sm1kWktFcTZNT2lxalNSUWpTTmVKbVJjUTBrCkl4cEZrREFUMDU5MEs4eGM5YWdG
        UlRCSkJxL1cvNmwwbEhLajF6Yi9NSWcKLS0tIGhBQThpQ0V5ZVlKY0cvQ0xwK2xq
        OElIN0VQaGFhUWRKYStoc1Y2aWpzVGMK6ugsX6bfAEiUPthlExD1YXADb1bF5BPN
        +lNoBTyVKxRjgpeG+LPmpdL6xJJBQgP/U52KzzhZKjAN3HZlRZj09w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-14T22:32:27Z"
  mac: ENC[AES256_GCM,data:migoWmiUVe4tgcPKlm/GgBjPrkAOJciKwc8yJoB3fOP9XQ9sG2LKfo5FkwWboFHB9ZvaR2ccFixcreZ8g6zAG0VumetgDuYN3P/oIu4hChjz5+McO+6odfMy1EpQ9BW23T7zYqE6Lmw2cudM1cLi9GMkLXv/Ca2kOvACF84MxLo=,iv:y0dqSHQc1DKhKarlh33tQMpgjHmFgl30xd0AGXXIBnI=,tag:FxrVafVeK6aAwuO/9K/b5g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
