apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: ts-router
spec:
  hostname: tailscale-router
  subnetRouter:
    advertiseRoutes:
      - "192.168.8.0/24"
      - "10.42.0.0/16"
      - "10.43.0.0/16"
      - "192.168.8.190/24"
      - "192.168.8.198/24"
      - "192.168.8.199/24"
      - "192.168.8.196/24"
      - "192.168.8.197/24"
  exitNode: true
  tags:
    - "tag:k8s"
