apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: tun-access
spec:
  statefulSet:
    pod:
      tailscaleContainer:
        resources:
          limits:
            kernel.org/tun: "1"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
            add:
              - NET_ADMIN
      labels:
        policy.gabe565.com/egress-kubeapi: "true"
        policy.gabe565.com/egress-nodes: "true"
        policy.gabe565.com/egress-world-with-lan: "true"
        policy.gabe565.com/egress-tailscale: "true"