---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: clickhouse
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: clickhouse
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        default_password: "{{ .CLICKHOUSE_DEFAULT_PASSWORD }}"
        admin_password: "{{ .CLICKHOUSE_ADMIN_PASSWORD }}"

        analytics_password: "{{ .CLICKHOUSE_ANALYTICS_PASSWORD }}"
        readonly_password: "{{ .CLICKHOUSE_READONLY_PASSWORD }}"
        backup_password: "{{ .CLICKHOUSE_BACKUP_PASSWORD }}"

        interserver_http_password: "{{ .CLICKHOUSE_INTERSERVER_PASSWORD }}"

        server_cert: "{{ .CLICKHOUSE_SERVER_CERT }}"
        server_key: "{{ .CLICKHOUSE_SERVER_KEY }}"
        ca_cert: "{{ .CLICKHOUSE_CA_CERT }}"

        s3_access_key: "{{ .S3_ACCESS_KEY }}"
        s3_secret_key: "{{ .S3_SECRET_KEY }}"

  dataFrom:
    - extract:
        key: clickhouse