---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clickhouse-cluster-role-binding
  labels:
    app.kubernetes.io/name: clickhouse
    security.samcloud.online/level: "restricted"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clickhouse-cluster-role
subjects:
  - kind: ServiceAccount
    name: clickhouse-service-account
    namespace: data-science 