---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clickhouse-service-account
  namespace: data-science
  labels:
    app.kubernetes.io/name: clickhouse
    security.samcloud.online/level: "restricted"