---
# PgBouncer Secrets
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgbouncer-secrets
  namespace: storage
  labels:
    app.kubernetes.io/name: pgbouncer
    app.kubernetes.io/component: credentials
    app.kubernetes.io/part-of: postgresql
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: pgbouncer-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          app.kubernetes.io/name: pgbouncer
      data:
        userlist.txt: |
          "{{ .POSTGRES_USER }}" "{{ .POSTGRES_PASSWORD }}"
          "authenticator" "{{ .PGBOUNCER_AUTH_PASSWORD }}"
          "pgbouncer_admin" "{{ .PGBOUNCER_ADMIN_PASSWORD }}"
          "pgbouncer_stats" "{{ .PGBOUNCER_STATS_PASSWORD }}"
  dataFrom:
    - extract:
        key: pgbouncer-secrets

---
# PgBouncer Admin Secret
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgbouncer-admin-secret
  namespace: storage
  labels:
    app.kubernetes.io/name: pgbouncer
    app.kubernetes.io/component: credentials
    app.kubernetes.io/part-of: postgresql
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: pgbouncer-admin-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: pgbouncer-secrets
        property: PGBOUNCER_ADMIN_PASSWORD