---
# PgBouncer Secrets
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgbouncer-secrets
  namespace: storage
  labels:
    app.kubernetes.io/name: pgbouncer
    app.kubernetes.io/component: credentials
    app.kubernetes.io/part-of: postgresql
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: pgbouncer-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          app.kubernetes.io/name: pgbouncer
      data:
        userlist.txt: |
          "{{ .pg_username }}" "{{ .pg_password }}"
          "authenticator" "{{ .pgbouncer_auth_password }}"
          "pgbouncer_admin" "{{ .pgbouncer_admin_password }}"
          "pgbouncer_stats" "{{ .pgbouncer_stats_password }}"
  dataFrom:
    - extract:
        key: pgbouncer-secrets

---
# PgBouncer Admin Secret
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgbouncer-admin-secret
  namespace: storage
  labels:
    app.kubernetes.io/name: pgbouncer-admin-secret
    app.kubernetes.io/component: credentials
    app.kubernetes.io/part-of: postgresql
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: pgbouncer-admin-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          app.kubernetes.io/name: pgbouncer-admin-secret
          app.kubernetes.io/component: credentials
          app.kubernetes.io/part-of: postgresql
      data:
        password: "{{ .password }}"
  dataFrom:
    - extract:
        key: pgbouncer-admin-secret