---
# PgBouncer Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pgbouncer
  namespace: storage
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: postgresql
automountServiceAccountToken: true