---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: loki
  namespace: observability
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 6.30.1
  url: oci://ghcr.io/grafana/helm-charts/loki
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: observability
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: loki
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: openebs
      namespace: storage
  values:
    deploymentMode: SingleBinary
    replicaCount: 2  # Minimum 2 for HA

    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 2
      memberlist:
        join_members:
          - "loki-memberlist.observability.svc.cluster.local:7946"

      storage_config:
        aws:
          s3: http://${accessKey}:${secretKey}@192.168.8.161:9000
          s3forcepathstyle: true
        tsdb_shipper:
          active_index_directory: /loki/index
          cache_location: /loki/index_cache
          cache_ttl: 24h

      schemaConfig:
        configs:
          - from: "2020-07-01"
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: index_
              period: 24h

      limits_config:
        retention_period: 14d

    singleBinary:
      replicas: 2  # Must match replicaCount
      persistence:
        enabled: true
        storageClass: openebs-hostpath
        size: 50Gi
        annotations: {}

    service:
      memberlist:
        enabled: true
        type: ClusterIP
        port: 7946

    ruler:
      storage:
        type: s3
        s3:
          endpoint: http://192.168.8.161:9000
          bucketnames: loki-data-ruler
          secretAccessKey:
            name: loki-s3-credentials
            key: secretKey
          accessKeyId:
            name: loki-s3-credentials
            key: accessKey
          s3ForcePathStyle: true
          insecure: true

    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        memory: 2Gi

    monitoring:
      enabled: true
      serviceMonitor:
        enabled: true

    sidecar:
      image:
        repository: ghcr.io/home-operations/k8s-sidecar
        tag: 1.30.3@sha256:39cca7abcad8f1621b9462d95f7d0e60301b92fcb0ff4de0ad4561859011cddf
      rules:
        searchNamespace: ALL
