---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: loki
  namespace: observability
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 6.30.1
  url: oci://ghcr.io/grafana/helm-charts/loki
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: observability
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: loki
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    deploymentMode: SingleBinary
    replicaCount: 3

    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 3

      # Storage configuration matching your requested format
      storage_config:
        aws:
          s3: http://$accessKey:$accessKey@192.168.8.161:9000
          s3forcepathstyle: true
        tsdb_shipper:
          active_index_directory: /loki/index
          cache_location: /loki/index_cache
          cache_ttl: 24h

      # Schema configuration
      schemaConfig:
        configs:
          - from: "2020-07-01"
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: index_
              period: 24h

      # Limits configuration
      limits_config:
        retention_period: 14d

    # SingleBinary configuration
    singleBinary:
      replicas: 3
      persistence:
        enabled: true
        storageClass: openebs-hostpath
        size: 50Gi
        annotations: {}

    # Ruler configuration
    ruler:
      storage:
        type: s3
        s3:
          endpoint: http://192.168.8.161:9000
          bucketnames: loki-data-ruler
          secretAccessKey:
            name: loki-s3-credentials
            key: accessKey
          accessKeyId:
            name: loki-s3-credentials
            key: secretKey
          s3ForcePathStyle: true
          insecure: true

    # Resources
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        memory: 2Gi

    # Monitoring
    monitoring:
      enabled: true
      serviceMonitor:
        enabled: true

    # Sidecar for rule loading
    sidecar:
      image:
        repository: ghcr.io/home-operations/k8s-sidecar
        tag: 1.30.3@sha256:39cca7abcad8f1621b9462d95f7d0e60301b92fcb0ff4de0ad4561859011cddf
      rules:
        searchNamespace: ALL
