---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: loki
  namespace: observability
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 6.30.1
  url: oci://ghcr.io/grafana/helm-charts/loki
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: observability
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: loki
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: openebs
      namespace: storage
  values:
    deploymentMode: SingleBinary
    replicaCount: 3
    monitoring:
      enabled: true
      serviceMonitor:
        enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: loki-s3-credentials

    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 3
      storage:
        type: s3
        bucketNames:
          chunks: lokibackup
          ruler: loki-data-ruler  # Matching your MinIO bucket name
        s3:
          endpoint: http://192.168.8.161:9000  # Matching your MinIO endpoint
          secretAccessKey:
            name: loki-s3-credentials
            key: secretKey  # Matching your secret key names
          accessKeyId:
            name: loki-s3-credentials
            key: accessKey      # Matching your access key names
          s3ForcePathStyle: true       # Required for MinIO
          insecure: true               # For HTTP connections
      schemaConfig:
        configs:
          - from: "2024-04-01"
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: loki_index_
              period: 24h

    singleBinary:
      persistence:
        enabled: true
        storageClass: openebs-hostpath
        size: 50Gi
        resizeInUseVolumes: false

    rulerConfig:
      storage:
        type: s3
        s3:
          bucket: loki-data-ruler
          endpoint: http://192.168.8.161:9000
          secretAccessKey:
            name: loki-s3-credentials
            key:  secretKey
          accessKeyId:
            name: loki-s3-credentials
            key: accessKey
          s3ForcePathStyle: true
          insecure: true

    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        memory: 2Gi

    sidecar:
      image:
        repository: ghcr.io/home-operations/k8s-sidecar
        tag: 1.30.3@sha256:39cca7abcad8f1621b9462d95f7d0e60301b92fcb0ff4de0ad4561859011cddf
      rules:
        searchNamespace: ALL
---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.10.3-standalone/service-v1.json
apiVersion: v1
kind: Service
metadata:
  name: loki-lb
  namespace: observability
  annotations:
    external-dns.alpha.kubernetes.io/hostname: loki.samcloud.online
    lbipam.cilium.io/ips: 192.168.8.102
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 3100
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki
