---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  instances: 3
  # renovate: datasource=docker depName=ghcr.io/cloudnative-pg/postgresql
  imageName: ghcr.io/cloudnative-pg/postgresql:17.2
  primaryUpdateStrategy: unsupervised
  storage:
    size: 30Gi
    storageClass: openebs-hostpath
    resizeInUseVolumes: false
  superuserSecret:
    name: cloudnative-pg-secret
  enableSuperuserAccess: true
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: 256MB
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true
  resources:
    requests:
      cpu: 300m
    limits:
      memory: 1Gi
  monitoring:
    enablePodMonitor: true
    enableServiceMonitor: true
  # renovate: datasource=github-tags depName=cloudnative-pg/barman-operator
  barmanObjectStore:
    enabled: true
    # renovate: datasource=github-tags depName=cloudnative-pg/barman-operator
    imageName: ghcr.io/cloudnative-pg/barman-operator:1.10.0
    imagePullPolicy: IfNotPresent
    # renovate: datasource=github-tags depName=cloudnative-pg/barman-operator
    version: 1.10.0
  # renovate: datasource=github-tags depName=cloudnative-pg/barman-operator
  barmanObjectStoreConfig:
    # renovate: datasource=github-tags depName=cloudnative-pg/barman-operator
    imageName: ghcr.io/cloudnative-pg/barman-operator-config:1.10.0
    imagePullPolicy: IfNotPresent
    # renovate: datasource=github-tags depName=cloudnative-pg/barman-operator
    version: 1.10.0
  # renovate: datasource=github-tags depName=cloudnative-pg/barman-operator
  barmanObjectStoreConfigSecret:
    name: cloudnative-pg-barman-object-store-config
  # renovate: datasource=github-tags depName=cloudnative-pg/barman-operator
  barmanObjectStoreConfigMap:
    name: cloudnative-pg-barman-object-store-config
  # renovate: datasource=github-tags depName=cloudnative-pg/barman-operator
  barmanObjectStoreConfigMapData:
    # renovate: datasource=github-tags depName=cloudnative-pg/barman-operator
    imageName: ghcr.io/cloudnative-pg/barman-operator-config:1.10.0
    imagePullPolicy: IfNotPresent
    # renovate: datasource=github-tags depName=cloudnative-pg/barman-operator
    version: 1.10.0

  backup:
    retentionPolicy: 10d
    barmanObjectStore: &barmanObjectStore
      data:
        compression: bzip2
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: s3://pgbackup/
      endpointURL: http://192.168.8.161:9000
      # Note: serverName version needs to be inclemented
      # when recovering from an existing cnpg cluster
      serverName: &currentCluster postgres-v3
      s3Credentials:
        accessKeyId:
          name: cloudnative-pg-secret
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: cloudnative-pg-secret
          key: AWS_SECRET_ACCESS_KEY
  externalClusters:
    - name: clusterBackup
      barmanObjectStore:
        destinationPath: s3://pgbackup/
        endpointURL: http://192.168.8.161:9000
        serverName: &previouscluster postgres-v2
        s3Credentials:
          accessKeyId:
            name: cloudnative-pg-secret
            key: AWS_ACCESS_KEY_ID
          secretAccessKey:
            name: cloudnative-pg-secret
            key: AWS_SECRET_ACCESS_KEY

---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.10.3-standalone/service-v1.json
apiVersion: v1
kind: Service
metadata:
  name: postgres-lb
  annotations:
    external-dns.alpha.kubernetes.io/hostname: postgres.samcloud.online
    lbipam.cilium.io/ips: 192.168.8.101
spec:
  type: LoadBalancer
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres
    role: primary
