---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-v16
  namespace: database
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4-5
  storage:
    size: 20Gi
    storageClass: local-hostpath
  enableSuperuserAccess: true
  superuserSecret:
    name: postgres-superuser
  postgresql:
    parameters:
      max_connections: "800"
      shared_buffers: "512MB"
      ssl_min_protocol_version: TLSv1.2
  bootstrap:
    recovery:
      source: &previousCluster postgres-v16-v2
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: &s3 s3://pgsql/
      endpointURL: &endpoint http://192.168.1.5:9000
      serverName: postgres-v16-v3
      s3Credentials:
        accessKeyId:
          name: minio-pgsql
          key: minio_s3_access_key
        secretAccessKey:
          name: minio-pgsql
          key: minio_s3_secret_access_key
  externalClusters:
    - name: *previousCluster
      barmanObjectStore:
        wal:
          compression: bzip2
          maxParallel: 8
        destinationPath: *s3
        endpointURL: *endpoint
        s3Credentials:
          accessKeyId:
            name: minio-pgsql
            key: minio_s3_access_key
          secretAccessKey:
            name: minio-pgsql
            key: minio_s3_secret_access_key
