apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres17-config
  namespace: storage
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: storage
data:
  postgresql.conf: |
    listen_addresses = '*'
    port = 5432
    max_connections = 20
    
    shared_buffers = 128MB
    effective_cache_size = 512MB
    work_mem = 2MB
    
    wal_level = replica
    max_wal_size = 1GB
    min_wal_size = 256MB
    
    log_min_duration_statement = 5000
    log_statement = 'ddl'

    shared_preload_libraries = 'pg_stat_statements'
    pg_stat_statements.max = 1000
    pg_stat_statements.track = top
    pg_stat_statements.save = on
    password_encryption = 'scram-sha-256'
    timezone = 'UTC'
    log_timezone = 'UTC'

  pg_hba.conf: |
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    local   all             all                                     trust
    host    all             all             127.0.0.1/32            scram-sha-256
    host    all             all             ::1/128                 scram-sha-256
    host    all             all             10.0.0.0/8              scram-sha-256
    host    all             all             192.168.8.0/24          scram-sha-256