---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postgres17-pdb
  namespace: storage
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: storage
spec:
  minAvailable: 2
  selector:
    matchLabels:
      cnpg.io/cluster: postgres17
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postgres17-primary-pdb
  namespace: storage
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: storage
spec:
  minAvailable: 1
  selector:
    matchLabels:
      cnpg.io/cluster: postgres17
      cnpg.io/instanceRole: primary 