---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgres17-backup
  namespace: storage
spec:
  cluster:
    name: postgres17
  schedule: "0 0 * * *"
  backupOwnerReference: self
  immediate: true
