---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/scheduledbackup_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgres
  namespace: storage
spec:
  schedule: "0 0 * * *" # Daily at midnight
  retentionPolicy:
    type: "keepLast"
    keepLast: 7 # Keep the last 7 backups
  storage:
  immediate: true
  backupOwnerReference: self
  cluster:
    name: postgres
