apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres17-metrics
  namespace: storage
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
      app.kubernetes.io/component: database
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics