apiVersion: v1
kind: Service
metadata:
  name: postgres-lb
  namespace: storage
  # labels:
  #   cnpg.io/cluster: postgres
  #   app.kubernetes.io/name: postgres
  #   app.kubernetes.io/component: database
  annotations:
    lbipam.cilium.io/ips: 192.168.8.101
    external-dns.alpha.kubernetes.io/hostname: postgres.samcloud.online
spec:
  type: LoadBalancer
  selector:
    cnpg.io/cluster: postgres
    cnpg.io/instanceRole: primary
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  sessionAffinity: ClientIP

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-ro
  namespace: storage
  # labels:
  #   cnpg.io/cluster: postgres
  #   app.kubernetes.io/name: postgres
  #   app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres
    cnpg.io/instanceRole: replica
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-rw
  namespace: storage
  # labels:
  #   cnpg.io/cluster: postgres
  #   app.kubernetes.io/name: postgres
  #   app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres
    cnpg.io/instanceRole: primary
  sessionAffinity: None