---
apiVersion: v1
kind: Service
metadata:
  name: postgres17
  namespace: storage
  labels:
    cnpg.io/cluster: postgres17
    cnpg.io/instanceRole: primary
  annotations:
    lbipam.cilium.io/ips: 192.168.8.101
    external-dns.alpha.kubernetes.io/hostname: postgres.samcloud.online
spec:
  type: LoadBalancer
  selector:
    cnpg.io/cluster: postgres17
    cnpg.io/instanceRole: primary
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
