---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: influxdb-pdb
  namespace: storage
  labels:
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/component: availability
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: influxdb