---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cloudnative-pg-analytics-worker-one-pdb
  namespace: storage
spec:
  minAvailable: 2
  selector:
    matchLabels:
      cnpg.io/cluster: cloudnative-pg-analytics-worker-one
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cloudnative-pg-analytics-worker-one-primary-pdb
  namespace: storage
spec:
  minAvailable: 1
  selector:
    matchLabels:
      cnpg.io/cluster: cloudnative-pg-analytics-worker-one
      cnpg.io/instanceRole: primary 