---
apiVersion: v1
kind: Service
metadata:
  name: cloudnative-pg-analytics-worker-one
  annotations:
    external-dns.alpha.kubernetes.io/hostname: postgres.samcloud.online
    lbipam.cilium.io/ips: 192.168.8.107
spec:
  type: LoadBalancer
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: cloudnative-pg-analytics-worker-one
    role: primary