---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cluster.yaml
  - ./gatus.yaml
  - ./scheduledbackup.yaml
  - ./service.yaml
  # - ./service-monitor.yaml
  - ./configmap.yaml
  - ./horizontal-pod-autoscaler.yaml
  - ./prometheusrule.yaml
  - ./rbac.yaml
  - ./pod-disruption-budget.yaml
  - ./pooler.yaml
