---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postgres-vector-pdb
  namespace: storage
spec:
  minAvailable: 2
  selector:
    matchLabels:
      cnpg.io/cluster: postgres-vector
      cnpg.io/instanceRole: replica
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postgres-vector-primary-pdb
  namespace: storage
spec:
  minAvailable: 1
  selector:
    matchLabels:
      cnpg.io/cluster: postgres-vector
      cnpg.io/instanceRole: primary 