---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: postgres-vector-pgbouncer-rw
spec:
  cluster:
    name: postgres-vector
  instances: 3
  type: rw
  monitoring:
    enablePodMonitor: true
  pgbouncer:
    poolMode: transaction
    parameters:
      max_client_conn: "1000"
      default_pool_size: "100"
      min_pool_size: "5"
      reserve_pool_size: "5"
      max_db_connections: "100"
      max_user_connections: "100"
      server_reset_query: "DISCARD ALL"
      server_check_delay: "30"
      server_check_query: "SELECT 1"
      server_lifetime: "3600"
      server_idle_timeout: "600"
      client_idle_timeout: "0"
      client_login_timeout: "60"

      tcp_keepalive: "true"
      tcp_keepalive_idle: "600"
      tcp_keepalive_interval: "30"
      tcp_keepalive_count: "3"
      tcp_user_timeout: "30000"

      query_timeout: "0"
      query_wait_timeout: "120"
      cancel_delay: "10"
      pkt_buf: "4096"

      log_connections: "true"
      log_disconnections: "true"
      log_pooler_errors: "true"