---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage

resources:
  - ./servicemonitor.yaml

commonLabels:
  app.kubernetes.io/name: pgbouncer
  app.kubernetes.io/component: monitoring
  app.kubernetes.io/part-of: postgresql
  environment: production

commonAnnotations:
  monitoring.coreos.com/enabled: "true"
  prometheus.io/scrape: "true" 