# Alertmanager HelmRelease - Production Ready
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alertmanager
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.1.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: openebs
      namespace: storage
  values:
    controllers:
      alertmanager:
        type: statefulset
        replicas: 3
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/name
                        operator: In
                        values:
                          - alertmanager
                  topologyKey: "kubernetes.io/hostname"

        statefulset:
          volumeClaimTemplates:
            - name: storage
              accessMode: ReadWriteOnce
              size: 1Gi
              storageClass: openebs-hostpath
              globalMounts:
                - path: /data

        containers:
          alertmanager:
            image:
              repository: quay.io/prometheus/alertmanager
              tag: v0.28.1
            args:
              - "--config.file=/etc/alertmanager/alertmanager.yml"
              - "--storage.path=/data"
              - "--cluster.listen-address=0.0.0.0:9094"
              - "--web.listen-address=:9093"
              - "--cluster.peer=alertmanager-0.alertmanager-headless.observability.svc:9094"
              - "--cluster.peer=alertmanager-1.alertmanager-headless.observability.svc:9094"
              - "--cluster.peer=alertmanager-2.alertmanager-headless.observability.svc:9094"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 256Mi

        serviceAccount:
          create: true
          name: alertmanager-sa

    service:
      app:
        ports:
          http:
            port: 9093

    persistence:
      config:
        type: configMap
        name: alertmanager
        globalMounts:
          - path: /etc/alertmanager
      secrets:
        type: secret
        name: alertmanager-secret
        globalMounts:
          - path: /etc/secrets

    route:
      app:
        hostnames:
          - alertmanager.samcloud.online
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
