apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vpa-recommender-pdb
  namespace: kube-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: recommender

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vpa-updater-pdb
  namespace: kube-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: updater
