# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:8MMOiYwWx3Jj2ny9PcyDBO+dNKV4DmUck0J2BRJGKESIg9IlhNr6IQ==,iv:syzlKcyvTSCGifllOtOkP/feLKB51G0i9OaO3zfT9H0=,tag:RSZORU8f5lSP12+TinGfXg==,type:str]
sops:
  age:
    - recipient: age1tudjnu8ra4zdanrhph0dhmdl8r4u0u6pfcwu0r4ayjtzja724vxqzfqjqt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrT0srVlVTYTF0T290a1pn
        WGQrdzhtZ01YUVZoSUYvLzFLY1lNZWdoOHpFCldaWC9JeDZCb0dxdHRkL2dQVjdt
        T2tuR2ZUc09tUkwyZWpkc2NnaSsrS0EKLS0tIFg0QzNOeGlPbmJGSlBKbHRkTmlR
        OVhLTXUrVzhWR2Q2Z09FckNOS2xaVzgKdWilmL0Dr7sfm+YM116nY7lvwtBdBDrh
        7MYY6wiQ11ltOveV/57t9SSy+MFz3szXj9evP86XgACOiNMfSZgjwQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-31T07:44:11Z"
  mac: ENC[AES256_GCM,data:OJBpDVbz/366T9c0GnP6928WtLjZgLhx+WIcxiRdkvyV6hYubckHThWcZ0se/rhwFBpDTo2H6J0m475WJxrMRCuu2jLKCudBxICqnDsYQpCljMi1/Pn/juyNxOL9T85wqWF5PQqhuzYDBgFai7icaOVuuzk6V3HS9UAoFLeHckk=,iv:wJKKcspwakijuGWTFYH4cQsZX10W5XXri/xwIDpH3bc=,tag:PQy3hdAsZXncNocuj5a/rA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
