# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:5xQbhSEbORw0sX3L0pqzXpVT9ZCiMKqWWw6FOBHz0d3ZMYNM6RWZdw==,iv:PQQw4joCNmaBr0A5WXW1+bXDi6c6IGraGj6k2hK/ubk=,tag:L3bHNRtY6GCKBJpZSvz8mA==,type:str]
sops:
  age:
    - recipient: age1tudjnu8ra4zdanrhph0dhmdl8r4u0u6pfcwu0r4ayjtzja724vxqzfqjqt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRXpvZnRTcmpueXFaNlFi
        WUp3MFVOWkxUT0c2WGdXYWwzYzNLd0lXbmxzCjdLdTJrcldYT3FBMFJwL1VSbHFn
        ZUdpdG9TZmtka2E2UVVLS0xpRHh3OWsKLS0tIG1MejhudWlaUWlZcFM4YkprcXlD
        dUh4UjBIYlZPT2ZlNUViY3FNdlU2YWMKhhrt4biL5kGTZJGOVA2J/ij+Ydrus9w7
        Qe6z3hQ2H29RVHCffjaAaUTDvgKAtFPLdlT1EA+wAoDRJPCsWTfTNg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-31T07:40:50Z"
  mac: ENC[AES256_GCM,data:VaCgU8ZCG2ALRA74WuzYjfCZu2162gQbW1387z6jCU4mi6c1UzRjjN7ktNR51FA8edEDUjdsDLVIOnHNEZXAcLIzPx7akn6IENGdio8Ku7Xo/+y/Uf3fP3+65jmxKAl0lgIpfbrHH5LHgFfqX0/lKx8tNLqAEOPrClMud7wttvI=,iv:p2mNDY1fQJ6EqUGfkX8xeR2fx8nA56ci/AJ4dzVpncg=,tag:/YDMIj7WMRJj9RrfKax7bA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
