# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:84IB0b9u2eiHWEbo2rm6N8gE5LUuJMLtLec6T7R16EmkboNHywLA8w==,iv:BULIt5pxaYOblo93nqAT7uosSXTrtN5taAVu0RINKjg=,tag:Dj0fRikTv1dwVrXEWnr1vw==,type:str]
sops:
  age:
    - recipient: age1tudjnu8ra4zdanrhph0dhmdl8r4u0u6pfcwu0r4ayjtzja724vxqzfqjqt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0QW85UUw0Z2g2K2VzdEdZ
        bXlVZ25qS2JBUnd6MEEza2ZTTFQwMVpyd1FzCm9YQlE3ZG9XOWlhckREbm1HVWFV
        QXAvZEpod2dVVE5WUDZDbndLV2xVUmMKLS0tIDYvdmM5aVR5cUhLb0toYXljL0NE
        TnJ5TUpKTFFSaVN2THFCYURSbXNSSVkKPZaRAlUW9XaLlOI4SAZJvC5aad+HOedT
        5m0YzElDx7Ev5OAOcVsqkMZfpbtjVQfDTB3lkZN2ZLXkoCYFyEXRQg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-31T23:57:51Z"
  mac: ENC[AES256_GCM,data:lCqZtAXa14EYtgHn5D8AztC0MGAyvaXrelpwPtHgrGEzaaufentegkurBuOwlfBI5+yR/HkV2Wdc/Hgrrf+kcE48nc+nyBMVb1vTxIR0msn97CMDnSYhkYnHE2ccJutL7H+D5hLh0CKm8x/nUlqMd2eKlxvx3YCZnrfl8HqJFl4=,iv:PIsCwr7EVnpB0wfkDyipg+zy2CzPIjHx6fig7U8dvc0=,tag:aiWzdaAX96/XkLmyrNJRpg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
