# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Cc16gO0Tt/zsxNDnE+p5fwZW3/T6YuBwqP57rrLOkPo93YRp6QURqQ==,iv:2XEwzqt8HMCNBjUmCBoj11ui1/WLwMGeAguAPIOkhv0=,tag:bAjmlQqFi5UZoiRMA3pnIw==,type:str]
sops:
  age:
    - recipient: age1pne9nvyh4n25fqwn3pdvykrpd5jxm6gazcpmtkgmg9xpy3vfv96qwxmehh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYU21zNlRJb2RuRXdPc2hR
        QnFpb24rSzJ0VmlNQTJ0OWcyR2JRdVM5MXhvCmxWZWkrRmtJdnFiVjBaNkcrMU9T
        dkU2L3pqSURZY1czZ01NRm9nZEdISTQKLS0tIGpjVHpZM0IvM0dFUytxdkp1NXdh
        Qkd0YVNFa0VUYVdnNG5xdVlZUkxKN00K24bWfewpGzmg35i2ZiRSKgrcX5fhl5C1
        YT57lQ2aNg3QET03QipMwt+SsJSvUsYkrW44DGo63Z5ja1Ra0rDNcA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-14T22:32:27Z"
  mac: ENC[AES256_GCM,data:as+CWCY0O+O2aX4IjI75WfyHbYzWdqzL2FcaaE3ZDUUsFK8CguxzA2UG51bDrgBdIpw1KsHCw58tEmUJd3cMbt7AAtHfvFzzmTW2UHHM/t92+Z6AOAwwiBz1EM0zSBqx+IZT0ApLco0PeSj27QAq8JZrBzAcLZAITEWRHSGUOG0=,iv:TE5ElBW89JWvYiBfa2RotI2ssmK2Xw2gl/pdJQ0TN9I=,tag:8DDBtlAwBsAxxCaKCoGpRQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
