# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.8.136:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.8.136"
  - "samcloud.online"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "control-plane"
    ipAddress: "192.168.8.173"
    installDisk: "/dev/sdb"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/24f6f9b3fa0a43b50155de92ce0e1288f6e93f97c9a92658df9a9b0489de908c
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "40:b0:34:35:6a:21"
        dhcp: false
        addresses:
          - "192.168.8.173/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.8.1"
        mtu: 1500
        vip:
          ip: "192.168.8.136"
  - hostname: "worker-node-1"
    ipAddress: "192.168.8.172"
    installDisk: "/dev/sdb"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/24f6f9b3fa0a43b50155de92ce0e1288f6e93f97c9a92658df9a9b0489de908c
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "c8:d3:ff:3b:e5:e5"
        dhcp: false
        addresses:
          - "192.168.8.172/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.8.1"
        mtu: 1500
        vip:
          ip: "192.168.8.136"
  - hostname: "worker-node-2"
    ipAddress: "192.168.8.171"
    installDisk: "/dev/sdb"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/24f6f9b3fa0a43b50155de92ce0e1288f6e93f97c9a92658df9a9b0489de908c
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "c8:d3:ff:3b:e6:34"
        dhcp: false
        addresses:
          - "192.168.8.171/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.8.1"
        mtu: 1500
  - hostname: "worker-node-3"
    ipAddress: "192.168.8.170"
    installDisk: "/dev/sdb"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/24f6f9b3fa0a43b50155de92ce0e1288f6e93f97c9a92658df9a9b0489de908c
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "40:b0:34:35:6a:1f"
        dhcp: false
        addresses:
          - "192.168.8.170/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.8.1"
        mtu: 1500
        vip:
          ip: "192.168.8.136"
  - hostname: "worker-node-4"
    ipAddress: "192.168.8.169"
    installDisk: "/dev/sdb"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/24f6f9b3fa0a43b50155de92ce0e1288f6e93f97c9a92658df9a9b0489de908c
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "c8:d3:ff:3b:04:ca"
        dhcp: false
        addresses:
          - "192.168.8.169/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.8.1"
        mtu: 1500
        vip:
          ip: "192.168.8.136"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"
  - "@./patches/global/machine-openebs.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"

