{
 "title": "APC SRT1500RMXLA UPS",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Device",
    "query": "label_values(upsIdentModel,instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Output Load",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "upsOutputPercentLoad{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Output Power",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "format": "voltamp",
   "valueName": "current",
   "targets": [
    {
     "expr": "0.1*upsOutputCurrent{instance=\"$instance\"}*upsOutputVoltage{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Battery Capacity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "upsEstimatedChargeRemaining{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Run Time Remaining",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "expr": "upsEstimatedMinutesRemaining{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Time on Battery",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "format": "m",
   "valueName": "avg",
   "targets": [
    {
     "expr": "upsSecondsOnBattery{instance=\"$instance\"}*60"
    }
   ]
  },
  {
   "title": "Battery Temperature",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "upsBatteryTemperature{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "upsInputVoltage{instance=\"$instance\"}",
     "legendFormat": "Line Input"
    },
    {
     "expr": "upsOutputVoltage{instance=\"$instance\"}",
     "legendFormat": "Output"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "upsInputFrequency{instance=\"$instance\"}",
     "legendFormat": "Input"
    },
    {
     "expr": "upsOutputFrequency{instance=\"$instance\"}",
     "legendFormat": "Output"
    }
   ]
  },
  {
   "title": "Output Current",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "expr": "upsOutputCurrent{instance=\"$instance\"}",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "upsBatteryVoltage{instance=\"$instance\"}",
     "legendFormat": "Voltage"
    }
   ]
  },
  {
   "title": "Battery Current",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "expr": "upsBypassCurrent{instance=\"$instance\"}",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Total DC Current",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 14 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "expr": "upsOutputCurrent{instance=\"$instance\"}",
     "legendFormat": "Current"
    }
   ]
  }
 ]
}