---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc-v2
  namespace: storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 50Gi
