apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kepler
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: kepler
      version: 0.6.0
      sourceRef:
        kind: HelmRepository
        name: kepler
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    podAnnotations:
      alloy.otel.dev/logs: "true"
      alloy.otel.dev/source: "kepler"

    resources: {}

    extraEnvVars:
      KEPLER_LOG_LEVEL: "1"
      ENABLE_GPU: "true"
      ENABLE_QAT: "true"
      ENABLE_EBPF_CGROUPID: "true"
      EXPOSE_HW_COUNTER_METRICS: "true"
      EXPOSE_IRQ_COUNTER_METRICS: "true"
      EXPOSE_CGROUP_METRICS: "true"
      ENABLE_PROCESS_METRICS: "true"
      CPU_ARCH_OVERRIDE: ""
      CGROUP_METRICS: "*"

    securityContext:
      privileged: true

    extraVolumeMounts:
      - name: cpu-metrics
        mountPath: /dev/cpu
        readOnly: true
    extraVolumes:
      - name: cpu-metrics
        hostPath:
          path: /dev/cpu
          type: Directory

    canMount:
      usrSrc: false

    serviceMonitor:
      enabled: true
      attachMetadata:
        node: true

    redfish:
      enabled: false
