---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: observability
spec:
  interval: 15m
  chart:
    spec:
      chart: tempo
      version: 1.21.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: openebs
      namespace: storage
  values:
    replicas: 2
    tempo:
      extraEnv:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio-credentials-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials-secret
              key: AWS_SECRET_ACCESS_KEY
      reportingEnabled: false
      metricsGenerator:
        enabled: true
        remoteWriteUrl: "http://mimir-nginx.observability.svc.cluster.local:80/api/v1/push"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      distributor:
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      ingester:
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
          limits:
            cpu: "1"
            memory: 2Gi
      querier:
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: "1"
            memory: 1Gi
      queryFrontend:
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      compactor:
        # Replicas for compactor are often 1, overriding global if necessary
        # replicas: 1
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi
      storage:
        trace:
          backend: s3
          s3:
            bucket: tempo-traces-8g2h1j
            endpoint: http://192.168.8.161:9000
            access_key: "" # Overridden by env var
            secret_key: "" # Overridden by env var
            insecure: true # For HTTP endpoint
            s3ForcePathStyle: true
    persistence:
      enabled: false
    tempoQuery:
      ingress:
        enabled: true
        ingressClassName: external
        className: external
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - &host "tempo-query.samcloud.online"
        tls:
          - secretName: istio-prod-cert-tls
            hosts:
              - *host
    serviceMonitor:
      enabled: true
# valuesFrom block removed
