---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openbooks-pvc
  namespace: services
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 8Gi
  storageClassName: openebs-hostpath
