---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./vernemq.yaml
  - ./node-exporter.yaml
  - ./pikvm.yaml
  - ./onepassword.yaml
  - ./smartctl-exporter.yaml
  - ./zigbee-controller.yaml
