---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  namespace: services
  name: schemas
  labels:
    strimzi.io/cluster: hoohoot
spec:
  partitions: 1
  replicas: 2
  config:
    cleanup.policy: compact
