---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: &app linkding
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  suspend: false
  dependsOn:
    # - name: external-ingress-nginx
    # - name: network
    - name: onepassword
      namespace: external-secrets
  path: ./kubernetes/apps/default/linkding/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  interval: 30m
  retryInterval: 1m
  timeout: 3m
