---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: network
spec:
  interval: 30m
  chart:
    spec:
      chart: tailscale-operator
      version: 1.88.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    operatorConfig:
      hostname: "tailscale-operator"
      podLabels:
        policy.gabe565.com/egress-kubeapi: "true"
        policy.gabe565.com/egress-nodes: "true"
        policy.gabe565.com/egress-world: "true"
      image:
        repository: ghcr.io/tailscale/k8s-operator
        tag: v0.1.0
      defaultTags:
        - "tag:k8s"
        - "tag:k8s-operator"
    apiServerProxyConfig:
      mode: "true"
    proxyConfig:
      image:
        repository: ghcr.io/tailscale/tailscale
      defaultProxyClass: default
  valuesFrom:
    - kind: Secret
      name: tailscale-operator-secret
      valuesKey: client_id
      targetPath: oauth.clientId
    - kind: Secret
      name: tailscale-operator-secret
      valuesKey: client_secret
      targetPath: oauth.clientSecret
