---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless-ai
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: paperless-ai-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        PAPERLESS_API_TOKEN: "{{ .PAPERLESS_API_TOKEN }}"
        PAPERLESS_USERNAME: "{{ .PAPERLESS_API_USER }}"
        CUSTOM_API_KEY: "{{ .OPENROUTER_PAPERLESSAI_API_KEY }}"
  dataFrom:
    - extract:
        key: paperless
    - extract:
        key: openrouter
