---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    citus-cluster: cloudnative-pg-analytics-worker-four
  name: cloudnative-pg-analytics-worker-four
  namespace: storage
spec:
  minAvailable: 2
  selector:
    matchLabels:
      cnpg.io/cluster: cloudnative-pg-analytics-worker-four
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    citus-cluster: cloudnative-pg-analytics-worker-four
  name: cloudnative-pg-analytics-worker-four
  namespace: storage
spec:
  minAvailable: 1
  selector:
    matchLabels:
      cnpg.io/cluster: cloudnative-pg-analytics-worker-four
      cnpg.io/instanceRole: primary 