---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale
  namespace: network
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: tailscale
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        tailscale_auth_key: "{{ .tailscale_auth_key }}"
  dataFrom:
    - extract:
        key: tailscale
  refreshInterval: 15m 