
---
# External Secret for Tailscale resources (includes ts_authkey)
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale
  namespace: network
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: tailscale
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: tailscale
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: tailscale
        property: client_secret
    - secretKey: ts_authkey
      remoteRef:
        key: tailscale
        property: ts_authkey
  refreshInterval: 15m 