---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: tailscale-pdb
  namespace: network
  labels:
    app.kubernetes.io/name: tailscale
    app.kubernetes.io/component: network
spec:
  maxUnavailable: 0
  
  selector:
    matchLabels:
      app.kubernetes.io/name: tailscale
      app.kubernetes.io/instance: tailscale 