---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tailscale
  namespace: network
  labels:
    app.kubernetes.io/name: tailscale
    app.kubernetes.io/component: storage
  annotations:
    volume.beta.kubernetes.io/storage-class: "openebs-hostpath"
    backup.velero.io/backup-volumes: "tailscale"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem 