---
# Backup Secret for S3 Configuration
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-backup
  namespace: storage
  labels:
    app.kubernetes.io/name: postgresql-backup
    app.kubernetes.io/component: credentials
    app.kubernetes.io/part-of: postgresql
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: postgres-backup
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
          backup.cnpg.io/credentials: "true"
      data:
        minio_access_key_id: "{{ .minio_access_key_id }}"
        minio_secret_access_key: "{{ .minio_secret_access_key }}"
        s3_endpoint_url: "{{ .s3_endpoint_url }}"
        s3_bucket_name: "{{ .s3_bucket_name }}"
  dataFrom:
    - extract:
        key: postgres-backup