---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg-backup
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      cnpg-backup:
        type: cronjob
        cronjob:
          concurrencyPolicy: Forbid
          schedule: "59 * * * *"
        pod:
          restartPolicy: OnFailure
          securityContext:
            fsGroup: 1022
            runAsGroup: 1022
            runAsUser: 1022
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                          - "amd64"
        containers:
          app:
            image:
              repository: ghcr.io/cloudnative-pg/postgresql
              # renovate: datasource=docker depName=ghcr.io/cloudnative-pg/postgresql versioning=redhat
              tag: 17.5-5
            env:
              PGHOST: 192.168.8.101
              PGPORT: "5432"
              PGUSER: postgres
              PGPASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: cloudnative-pg-secret
                    key: password
              TZ: ${TIMEZONE:=Etc/UTC}
            command:
              - "/bin/sh"
            args:
              - "-c"
              - "pg_dumpall -U $PGUSER | gzip > /mnt/hoemlab/backup/data/k8s/postgres/backup/postgres-cluster.dump.gz"
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 512Mi
    persistence:
      backup:
        type: nfs
        server: 192.168.8.161
        path: /mnt/hoemlab/backup/data/k8s/postgres/backup
