---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: observability
spec:
  path: ./kubernetes/apps/observability/kube-prometheus-stack/app
  prune: true
  dependsOn:
    - name: openebs
      namespace: storage
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 5m
