apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: observability
  labels:
    app.kubernetes.io/name: goldilocks
    app.kubernetes.io/component: resource-optimization
    app.kubernetes.io/part-of: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: goldilocks
      version: 7.0.1
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controller:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          interval: 30s
          scrapeTimeout: 10s

    dashboard:
      enabled: true
      replicaCount: 1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/icon: mdi:chart-bell-curve
        hosts:
          - host: &host "goldilocks.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    vpa:
      enabled: true
      recommender:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        extraArgs:
          - --recommendation-margin-fraction=0.15
          - --pod-recommendation-min-cpu-millicores=10
          - --pod-recommendation-min-memory-mb=50

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 30s
        scrapeTimeout: 10s