apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:vvupKaCOYFrLgDjEka1g,iv:gh/69i6GSap+DCmEQrfrvMaUjKlDAMYhQkE05QI9QlA=,tag:6u3rcTyh2xotuMnnsjme7Q==,type:str]
sops:
  age:
    - recipient: age1tudjnu8ra4zdanrhph0dhmdl8r4u0u6pfcwu0r4ayjtzja724vxqzfqjqt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcVVvVlFFWUoreWFPQjNu
        R0ZsYjNwR1VwemlSaCtiSmRGVjlFY1JhOXo4CnBoSm1GbmdLY3d0UTUxeDM4TEdy
        SVdQVkxLTFE0Tks4Q3k4OVhiOFEwNUkKLS0tIHFKNDRlQTNxT0hTR01NR29MU2ta
        YU1jZXhOU3dXaFBpOTdCWm9zVHUvdUUKMZyVLT0O8yZcXRH4vyptKBYWULT9WMIK
        AI7fqZgu0S7LWXMT+qTbH+dwWdnfXFAxsUbAIW7axM9/8U8IXACkdw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-31T23:57:51Z"
  mac: ENC[AES256_GCM,data:y4rlyroHfDZLauCYzteUP9AN7CZvHapf2w4CiT45gSwXfTZ2h7cPE+zt3J9xwqHYIU8KJuHFEjQccEwcu5jpxsfd3cFNZ8K0eNjO5Si8hbgFeJz0U6pmDlUN01Nmb2XpySQ6n9x8+lCfqqSywdPwRMcR+cs4QPimzedVPBqXekk=,iv:NFRY9Rrzl2hkl0RoRKeTiKj0RkOKoLnjb9iUKBXRGFE=,tag:br6c5WPxsaSsKnfcV2fRYA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
