apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:DcRl+ubmKqU1lLT5ziGe,iv:FWUNJeoS2gagv88drwY2qg+INnM8h+mrOgnujMzNL6A=,tag:aszrtWJhV818r0EjcJA38g==,type:str]
sops:
  age:
    - recipient: age1tudjnu8ra4zdanrhph0dhmdl8r4u0u6pfcwu0r4ayjtzja724vxqzfqjqt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaGUyYlMvaTRHbGY3VkEy
        a05DTXhqVDZ2RWplYmNVYmZNZnhOLzFmS2lzCkNkeU5lbzZFZDJHUWk3bWhqYnJx
        aXY2T0Q5bHo4ZGlmNFlNUXJ2V3EzRmsKLS0tIGsxbDNZakErQk1wTjFXM0lXVW1o
        YVFSQUM1L1diWFpiVGk1VGluNEp6bTAKndwt8l9dE8AD4SHyAvHmFMDU8vkkgPth
        k5Jk9BstQw9RE/3g8662caHYho0Fw3mcPfkS5oYMi+tiYKVLLhxxvQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-31T07:44:11Z"
  mac: ENC[AES256_GCM,data:k4c0fM1JCXgRvC6T9y0S4HxwGmQSih99BpR070HVOi8aS3O6kiBiUZEJ6/miJjkU4+yQ++nZYMy+7s7V/yEKaMMCfo+s7Gm0EHtP8MABtbuM/X70jhbTC/J84wal+AVIjDuCpxu5504P/iSU9izuNXB0E8BHPg915TkjtmEIMlA=,iv:9DAFm2A22zrPtbrxPl96COOjIQZ4EF0TV9e6V2PpHWw=,tag:OBymujoPd0I6bIHzKZ3cuw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
