apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:r/Kx2f5rhAfnTFXBH8AZ,iv:dQC8VcVgzgR5ezPj+z2JsKjR5uGq/kxM1wnn+Cp0wwE=,tag:/v8C8nYogFFDNKi23nx0sQ==,type:str]
sops:
  age:
    - recipient: age1pne9nvyh4n25fqwn3pdvykrpd5jxm6gazcpmtkgmg9xpy3vfv96qwxmehh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bk5ieTBBU1RUVkJtdGZI
        SlJ0R0ttaWJ5MnVaMXdsUXJwenNlNW1oYzFvCkkwejdISVdEVTFZek0yN0NVK2tl
        ZG1OYXFwd21DN3lQZnVjYlJPaU5hWkUKLS0tIGRlZElvd2h4TlkyWHdYN0ZFSi9P
        NE14QTBsUUlPcDhuUEtWNjUwc2dzTmcKyTzflPlXzFdeQD6aia18vGVFNznmFq9M
        axasUybV5HXE+d0NOWVKYzP3m6OOwyMh8jiLeFrR/14r0moMzVAzjg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-14T22:32:27Z"
  mac: ENC[AES256_GCM,data:z2o9iEqi32wa7K5YXXyvUkqnMR9cfXpfGpCLnJuSSH0rIsqxcG7BRHLFEzp3BT1osAlO9Gu+LSut443j9GmotxFAuQyG+zJuDW8dQwspfbLjhowCFYsFqE2z39huKW4y/ew7UkYBiYKUPcamcVA83KMjT3A6iFjh+IN543guR0E=,iv:r0V/cUKwvpGjLWrBc6+q/6JEmv4yTcNhctbpF3N8Rbo=,tag:H790+Llt4IauFy+Jmq9+gA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
