apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:5E5r7BLbRZGSsc+PKR9MfYro10mB3vNLbn51rT8gUvxgD9LHSLQmrFHHV76+GrkKMQESNeUa9MSiUufDx8q46Zs9wbPCXuNlf+A=,iv:uCZG+tF072c+HwrPdZFdefZHP8SBLRfANshThRvoqr4=,tag:KCiiHuyJ4TCnZi+E658RRw==,type:str]
sops:
  age:
    - recipient: age1tudjnu8ra4zdanrhph0dhmdl8r4u0u6pfcwu0r4ayjtzja724vxqzfqjqt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBY050d3pWVUtTQ3paTlFG
        VFNSNmZpN0p3c1MrZ3Bjby9zZ1dRTU1IUTFBCmRoaVZHaTFGdm84dHEwTlEwcUd0
        bE9wNWZtQ2RWYUxSRGFpUTVINUdpM1EKLS0tIGd3OTJXek41YzE1dmRmMDJhWTVp
        WmkrR2pvK0tJY3A2WWcrQ2MraXJWUGsKuLKLRVqwEidvD9wFUDLBRpCOtoRgLUmQ
        q6yvvK9CehB2IsCA+XhI566h4JsuROvVd5fFM/6iw8fTVpee4RTMWw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-31T07:40:50Z"
  mac: ENC[AES256_GCM,data:XlRTGJ++QMgVuUcATpta2etNXqgfSpLfuWOKLlAylf2VogeHh9HOvm5IBHrnBWlsXGsNJnax2Ebq9VlEnNdSb2h+RTPi+IQ3lyo6hutacZz5r18uv/B4pRocqu363VChdiudOV7u4VBN6YtBlLxgXE24hGnm/155DPGZR5IdDoA=,iv:Moi3RLkJMtRu1thlfYfZiSC13fMayTSHRH2OC56weB0=,tag:MlRPA4Z+lASC9W4jbP4MYA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
