---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: docuseal-secret
  namespace: kube-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: docuseal-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DOCUSEAL_DB_URI: |-
          postgres://{{ .DOCUSEAL__POSTGRES_USER }}:{{ .DOCUSEAL__POSTGRES_PASS }}@postgres-v1-rw.databases.svc.cluster.local/docuseal
        INIT_POSTGRES_DBNAME: postgres
        INIT_POSTGRES_HOST: 192.168.8.101
        #INIT_POSTGRES_HOST: "{{ .GCP__POSTGRES_DB_APPS_HOST }}"
        INIT_POSTGRES_USER: "{{ .DOCUSEAL__POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .DOCUSEAL__POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .CNPG__POSTGRES_SUPER_PASS }}"
        #INIT_POSTGRES_SUPER_PASS: "{{ .GCP__POSTGRES_DB_APPS_SUPER_PASS }}"

  dataFrom:
    - find:
        path: DOCUSEAL__

    - find:
        path: CNPG__

    - find:
        path: GCP__
