---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tailscale
  namespace: network
spec:
  interval: 1h
  url: https://pkgs.tailscale.com/helmcharts
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tailscale
spec:
  interval: 1h
  chart:
    spec:
      chart: tailscale-operator
      version: 1.84.0
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: network
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    # TODO: currently not supported by the operator
    fullnameOverride: *app

    installCRDs: true

    ingressClass:
      enabled: false

    oauthSecretVolume:
      secret:
        secretName: tailscale-oauth

    operatorConfig:
      logging: debug
      hostname: "hive-operator"
      podAnnotations:
        reloader.stakater.com/auto: "true"
      defaultTags:
        - "tag:hive-operator"

    proxyConfig:
      defaultTags: "tag:hive"

    apiServerProxyConfig:
      mode: "true"
