---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing
  namespace: storage
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 8Gi
  storageClassName: openebs-hostpath
