---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app linkding
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      linkding:
        replicas: 2
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            # https://github.com/onedr0p/containers/blob/main/apps/postgres-init/entrypoint.sh
            env:
              INIT_POSTGRES_HOST: &dbHost 192.168.8.101
              INIT_POSTGRES_DBNAME: &dbName postgres
              INIT_POSTGRES_USER:
                valueFrom:
                  secretKeyRef:
                    name: &secret linkding-secret
                    key: LD_DB_USER
              INIT_POSTGRES_PASS:
                valueFrom:
                  secretKeyRef:
                    name: linkding-secret
                    key: LD_DB_PASSWORD
              INIT_POSTGRES_SUPER_PASS:
                valueFrom:
                  secretKeyRef:
                    name: linkding-secret
                    key: LD_DB_SUPER_PASSWORD
              INIT_POSTGRES_PORT: 5432
              INIT_POSTGRES_SSLMODE: disable
        containers:
          app:
            image:
              repository: docker.io/sissbruecker/linkding
              tag: 1.36.0-plus-alpine
            env:
              LD_DB_ENGINE: postgres
              LD_DB_DATABASE: *dbName
              LD_DB_HOST: *dbHost
              LD_DB_PORT: 5432
            envFrom:
              - secretRef:
                  name: *secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 9090
                  initialDelaySeconds: 10
                  periodSeconds: 5
                  timeoutSeconds: 10
                  failureThreshold: 30
              readiness: *probes
            resources:
              requests:
                cpu: 12m
                memory: 512M
              limits:
                # For HTML snapshot spike
                memory: 4Gi
    service:
      app:
        controller: linkding
        ports:
          http:
            port: *port
    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.samcloud.online"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Services
          gethomepage.dev/name: Bookmarks
          gethomepage.dev/icon: mdi-bookmark
        hosts:
          - host: "bookmarks.samcloud.online"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      data:
        existingClaim: linkding-pvc
        globalMounts:
          - path: /etc/linkding/data
