---
# PgBouncer Authentication Secret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgbouncer-auth
  namespace: storage
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/part-of: postgresql
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: pgbouncer-auth
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        userlist.txt: |
          "pgbouncer" "{{ .PGBOUNCER_PASSWORD }}"
          "postgres" "{{ .POSTGRES_PASSWORD }}"
      stringData:
        PGBOUNCER_PASSWORD: "{{ .PGBOUNCER_PASSWORD }}"
        POSTGRES_PASSWORD: "{{ .POSTGRES_PASSWORD }}"
  data:
    - secretKey: PGBOUNCER_PASSWORD
      remoteRef:
        key: pgbouncer-auth
        property: PGBOUNCER_PASSWORD
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: pgbouncer-auth
        property: POSTGRES_PASSWORD

---
# PgBouncer Exporter Secret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgbouncer-exporter-secret
  namespace: storage
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/part-of: postgresql
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: pgbouncer-exporter-secret
    creationPolicy: Owner
  data:
    - secretKey: PGBOUNCER_PASSWORD
      remoteRef:
        key: pgbouncer-exporter-secret
        property: PGBOUNCER_PASSWORD